### ISSUE TITLE
Invalid URL 'None': No schema supplied

### ISSUE THREAD

**Issue by UdhavPawar** [Proxlight/Proxlight-Designer-v2#2]
👋  Proxlight Team, nice to meet you. 

First of all love your content 💯 have been a YouTube sub for a long time :)
Was following your latest Proxlight Designer 2021 [youtube video](https://www.youtube.com/watch?v=Qf5cnJDSolE) 

### Issue:
- Followed all installation steps and have latest v2 designer running on mac by running `python3 Proxlight Designer.py`.
- Followed documentation and fed the right Figma document link (which is `https://www.figma.com/file/kji5xUqZwCfjoVYmQDk7FV/Auto-Attender?node-id=0%3A1` also tried input as `https://www.figma.com/file/kji5xUqZwCfjoVYmQDk7FV/Auto-Attender` but same error), new Figma token and a path to export code.
- After clicking create I'm facing this error:

```
udhavpawar@udhav:~/Downloads/Proxlight-Designer-v2-main/Proxlight Designer Source File$ python3 Proxlight\ Designer.py 
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/Users/udhavpawar/Downloads/Proxlight-Designer-v2-main/Proxlight Designer Source File/Proxlight Designer.py", line 336, in btn_clicked
    generate_code(token,URL, output_path)
  File "/Users/udhavpawar/Downloads/Proxlight-Designer-v2-main/Proxlight Designer Source File/Proxlight Designer.py", line 178, in generate_code
    image_link = requests.get(response.json()["images"][item_id])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
```
- Any insights on tackling it is appreciated. 

Let me know if any additional info is required :)

**Comment by Proxlight** [comment]
Sorry for that but we are working on the Mac edition. We are also trying to resolve all the issues, we will provide a fresh link for the Mac user when it is resolved.
Regards,
Pratyush ( From Proxlight )
